Algoritmo "primeiroExercicio"

Var

   x, y : inteiro


Inicio

   escreva("Digite x:")
   leia(x)
   escreva("Digite y:")
   leia(y)

   enquanto x <> y faca
      se x < y entao
         escreval("CRESCENTE")
      senao
         escreval("DECRESCENTE")
      fimse

      escreval("Digite outros dois numeros:")
      escreva("Digite x:")
      leia(x)
      escreva("Digite y:")
      leia(y)

   fimenquanto

Fimalgoritmo