Algoritmo "nonoExercício"

Var

  distanciaPercorrida : inteiro
  combustivelGasto : real
  consumoMedio : real

Inicio

   escreva("Digite a distancia percorrida:")
   leia(distanciaPercorrida)
   escreva("A quantidade de combustível gasto:")
   leia(combustivelGasto)
   
   consumoMedio <- distanciaPercorrida / combustivelGasto
   
   escreva("O consumo medio eh =", consumoMedio:8:3)


Fimalgoritmo